### ISSUE TITLE
Nodes are movable

### ISSUE THREAD

**Issue by phcerdan** [KitwareMedical/SRepExtension#3]
Nodes can be moved, I don't think this is expected behavior, see animation. @vicory 

![srep_moving _nodes](https://user-images.githubusercontent.com/3021667/42589377-bd190cc2-850e-11e8-897e-904658582ffd.gif)

**Comment by vicory** [comment]
Ultimately the nodes should probably be movable but moving them would cause the things attached to that node (quads, spokes) to adjust with it. I can show you how this currently works in Pablo if you want a demo. If we don't want to implement that right now then they should probably be non-movable.

**Comment by bpaniagua** [comment]
@vicory @phcerdan 
Agreeing with Jared on this

**Comment by phcerdan** [comment]
Makes sense. I we go to emulate the other software with such a great name, I do think we need a mrmlNode to have all these models connected.

![image](https://user-images.githubusercontent.com/3021667/42589885-5ec1ab14-8510-11e8-9a68-1853c89ab5b4.png)

I will make them non-movable until then.
