### ISSUE TITLE
About test data

### ISSUE THREAD

**Issue by phcerdan** [KitwareMedical/SRepExtension#4]
Hey @ZhiyLiu, I saw you added test data at the top level, [in this commit](https://github.com/KitwareMedical/SRepExtension/commit/05888a5af151d6653e85212adbf233334d1c27b0)
The test data is already in: https://github.com/KitwareMedical/SRepExtension/tree/master/SkeletalRepresentationVisualizer/Testing/test_data.

Do you think that `Testing/test_data` location is ok? If yes, we shouldn't have duplicate files, and we could rever that commit. I can do it, but not sure if you are working locally in any other update. Could you revert it? Thanks!

**Comment by ZhiyLiu** [comment]
You are right. I added it for the sake of the manual I’m writing. I’ll take care of it.

**Comment by phcerdan** [comment]
@ZhiyLiu I am closing this issue if that was solved, thanks!

Also, for the future, I would recommend that, instead of pushing directly to master, it is best practice to develop changes in a branch, and then open a Pull Request here to merge that branch in master.

This allow two things, first you can develop features in parallel in different branches, and second, it allows the opportunity to review the changes by others more easily.

For minor things I think is still ok to push directly to master, specially because we don't have any continuous integration to test the changes.
